# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/NeuralNetworks/neuralNetwork/verification_ph2/MNIST_NETS/myProject1.runs/synth_1/zyNet.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/NeuralNetworks/neuralNetwork/verification_ph2/MNIST_NETS/myProject1.cache/wt [current_project]
set_property parent.project_path C:/NeuralNetworks/neuralNetwork/verification_ph2/MNIST_NETS/myProject1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/NeuralNetworks/neuralNetwork/verification_ph2/MNIST_NETS/myProject1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_10.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_11.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_12.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_13.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_14.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_15.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_16.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_17.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_18.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_19.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_20.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_21.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_22.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_23.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_24.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_25.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_26.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_27.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_28.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_29.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_1_9.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_10.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_11.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_12.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_13.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_14.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_15.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_16.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_17.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_18.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_19.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_20.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_21.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_22.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_23.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_24.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_25.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_26.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_27.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_28.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_29.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_2_9.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_3_9.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/b_4_9.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/sigContent.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_10.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_11.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_12.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_13.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_14.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_15.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_16.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_17.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_18.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_19.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_20.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_21.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_22.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_23.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_24.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_25.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_26.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_27.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_28.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_29.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_1_9.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_10.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_11.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_12.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_13.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_14.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_15.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_16.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_17.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_18.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_19.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_20.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_21.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_22.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_23.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_24.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_25.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_26.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_27.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_28.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_29.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_2_9.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_3_9.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_0.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_1.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_2.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_3.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_4.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_5.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_6.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_7.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_8.mif
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/w_4_9.mif
}
read_verilog -library xil_defaultlib {
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/Layer_1.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/Layer_2.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/Layer_3.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/Layer_4.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/Sig_ROM.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/include.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/Weight_Memory.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/axi_lite_wrapper.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/maxFinder.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/neuron.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/relu.v
  C:/NeuralNetworks/neuralNetwork/verification_ph2/src/fpga/rtl/zynet.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top zyNet -part xc7z020clg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zyNet.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zyNet_utilization_synth.rpt -pb zyNet_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
